# Generated by Django 5.1.3 on 2024-12-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectnote',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectnote',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectNote',
        ),
    ]
