# Generated by Django 5.1.3 on 2024-12-25 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0006_alter_employee_belbin_test_result'),
        ('employers', '0004_verificationcode_employer'),
        ('projects', '0002_remove_projectnote_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='employers.employer')),
                ('skills_required', models.ManyToManyField(related_name='projects', to='employees.skill')),
            ],
        ),
    ]
