# Generated by Django 5.1.3 on 2024-12-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_assigned_employees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='assigned_employees',
            new_name='employees',
        ),
        migrations.DeleteModel(
            name='ProjectTeam',
        ),
    ]
