# Generated by Django 5.1.3 on 2024-12-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employer'),
        ('projects', '0002_remove_projectnote_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
