# Generated by Django 5.1.3 on 2024-12-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='availability',
        ),
    ]
