# Generated by Django 5.1.3 on 2025-01-11 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_remove_employee_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='BelbinScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=10)),
                ('score', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belbin_scores', to='employees.employee')),
            ],
        ),
    ]
