# Generated by Django 5.1.3 on 2025-03-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employeeskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeskill',
            name='proficiency_level',
            field=models.CharField(choices=[('1', 'Początkujący'), ('2', 'Średniozaawansowany'), ('3', 'Zaawansowany'), ('4', 'Ekspert')], default='2', max_length=20),
        ),
    ]
