# Generated by Django 5.1.3 on 2025-03-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_employeeskill_proficiency_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeskill',
            name='proficiency_level',
            field=models.CharField(choices=[('1', 'Junior'), ('2', 'Mid'), ('3', 'Senior')], default='2', max_length=20),
        ),
    ]
