# Generated by Django 5.1.3 on 2025-03-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_employeeskill_proficiency_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='skills/logos/'),
        ),
    ]
