# Generated by Django 5.1.3 on 2025-03-17 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_skill_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł')),
                ('description', models.TextField(verbose_name='Opis')),
                ('date_started', models.DateField(verbose_name='Data rozpoczęcia')),
                ('date_ended', models.DateField(blank=True, null=True, verbose_name='Data zakończenia')),
                ('image', models.ImageField(blank=True, null=True, upload_to='experiences/', verbose_name='Zdjęcie')),
                ('project_file', models.FileField(blank=True, null=True, upload_to='experience_files/', verbose_name='Plik projektu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Doświadczenie',
                'verbose_name_plural': 'Doświadczenia',
                'ordering': ['-date_started'],
            },
        ),
    ]
